config/routes.rb
LeftOverPie::Application.routes.draw do
  
  devise_for :users
  resources :causes
  root :to => "causes#index"

end

app/models/cause.rb
class Cause < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
before_filter :authenticate_user!
  # GET /causes
  # GET /causes.xml
  def index
    @causes = Cause.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @causes }
    end
  end

  # GET /causes/1
  # GET /causes/1.xml
  def show
    @cause = Cause.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cause }
    end
  end

  # GET /causes/new
  # GET /causes/new.xml
  def new
    @cause = Cause.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cause }
    end
  end

  # GET /causes/1/edit
  def edit
    @cause = Cause.find(params[:id])
  end

  # POST /causes
  # POST /causes.xml
  def create
    @cause = Cause.new(params[:cause])

    respond_to do |format|
      if @cause.save
        format.html { redirect_to(@cause, :notice => 'Cause was successfully created.') }
        format.xml  { render :xml => @cause, :status => :created, :location => @cause }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cause.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /causes/1
  # PUT /causes/1.xml
  def update
    @cause = Cause.find(params[:id])

    respond_to do |format|
      if @cause.update_attributes(params[:cause])
        format.html { redirect_to(@cause, :notice => 'Cause was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cause.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.xml
  def destroy
    @cause = Cause.find(params[:id])
    @cause.destroy

    respond_to do |format|
      format.html { redirect_to(causes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/views/causes/_form.html.erb
<%= form_for(@cause) do |f| %>
  <% if @cause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cause.errors.count, "error") %> prohibited this cause from being saved:</h2>

      <ul>
      <% @cause.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :causeName %><br />
    <%= f.text_field :causeName %>
  </div>
  <div class="field">
    <%= f.label :causeLink %><br />
    <%= f.text_field :causeLink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/causes/edit.html.erb
<h1>Editing cause</h1>

<%= render 'form' %>

<%= link_to 'Show', @cause %> |
<%= link_to 'Back', causes_path %>

app/views/causes/index.html.erb
<h1>Listing causes</h1>

<table>
  <tr>
    <th>Cause Name</th>
    <th>Cause Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @causes.each do |cause| %>
  <tr>
    <td><%= cause.causeName %></td>
    <td><%= cause.causeLink %></td>
    <td><%= link_to 'Show', cause %></td>
    <td><%= link_to 'Edit', edit_cause_path(cause) %></td>
    <td><%= link_to 'Destroy', cause, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cause', new_cause_path %>

app/views/causes/new.html.erb
<h1>New cause</h1>

<%= render 'form' %>

<%= link_to 'Back', causes_path %>

app/views/causes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cause Name:</b>
  <%= @cause.causeName %>
</p>

<p>
  <b>Cause Link:</b>
  <%= @cause.causeLink %>
</p>


<%= link_to 'Edit', edit_cause_path(@cause) %> |
<%= link_to 'Back', causes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeftOverPie</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
<div id="user_nav">
<% if user_signed_in? %>
Signed in as <%= current_user.email %>. Not you?
<%= link_to "Sign Out", destroy_user_session_path %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
<% end %>
</div>

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>